- name: "Install pipx tools"
  become: true
  become_user: root
  community.general.pipx:
    name: "{{ item.name }}"
    source: "{{ item.url }}"
    state: latest
    executable: "/usr/bin/pipx"
  loop:
    - { name: 'impacket', url: 'git+https://github.com/fortra/impacket.git' }
    - { name: 'netexec', url: 'git+https://github.com/Pennyw0rth/NetExec.git' }
    - { name: 'certipy-ad', url: 'git+https://github.com/ly4k/Certipy.git' }
    - { name: 'bloodhound-ce', url: 'git+https://github.com/dirkjanm/BloodHound.py.git@bloodhound-ce' }
