---
galaxy_info:
  author: kali-build
  description: Initialize Metasploit database (msfdb init)
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions: ["bookworm", "bullseye"]

dependencies: []
