---
galaxy_info:
  author: dswenningsen
  description: Install latest KasmVNC for Debian bookworm amd64
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - bookworm
dependencies: []
