---
- name: "Install Tmux"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copying Tmux Config"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_facts['env']['HOME'] }}/.tmux.conf"


