---
- name: Add NOPASSWD rule for the current user
  become: true
  lineinfile:
    dest: /etc/sudoers
    insertbefore: EOF
    regexp: "{{ ansible_facts['user_id'] }} ALL="
    line: "{{ item }}"
    validate: visudo -cf %s
  when: ansible_facts['user_id'] != 'root'
  with_items:
    - "{{ ansible_facts['user_id'] }}\tALL=(ALL) NOPASSWD:ALL"